files:
  - source: /docs/**/*
    translation: >-
      /i18n/%locale_with_underscore%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /i18n/en_US/**/*
    translation: /i18n/%locale_with_underscore%/**/%original_file_name%
